CREATE DATABASE wa_gateway;
USE wa_gateway;

-- Users table
CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('administrator', 'admin', 'user') DEFAULT 'user',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- WA Connections table
CREATE TABLE WAConnections (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phoneNumber VARCHAR(20) NOT NULL UNIQUE,
  status ENUM('connected', 'disconnected', 'authenticating') DEFAULT 'disconnected',
  qrCode TEXT,
  sessionData TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Messages table (corrected with backticks around reserved words)
CREATE TABLE Messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  `from` VARCHAR(20) NOT NULL,
  `to` VARCHAR(20) NOT NULL,
  body TEXT NOT NULL,
  mediaUrl VARCHAR(255),
  isGroup BOOLEAN DEFAULT false,
  status ENUM('received', 'sent', 'pending', 'failed') DEFAULT 'received',
  processed BOOLEAN DEFAULT false,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Sunscreen table
CREATE TABLE Sunscreen (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  sender VARCHAR(100) NOT NULL,
  amount INT NOT NULL,
  mediaUrl VARCHAR(255),
  googleDriveUrl VARCHAR(255),
  keterangan TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Shopsign table
CREATE TABLE Shopsign (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  sender VARCHAR(100) NOT NULL,
  amount INT NOT NULL,
  mediaUrl VARCHAR(255),
  googleDriveUrl VARCHAR(255),
  keterangan TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Mitra table
CREATE TABLE Mitra (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  sender VARCHAR(100) NOT NULL,
  amount INT NOT NULL,
  mediaUrl VARCHAR(255),
  googleDriveUrl VARCHAR(255),
  keterangan TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
